"""Check the candle cache against itself: does a 1d bar equal its own 24 1h bars?

No network, no ticks, and it covers the **entire** history rather than the month
a tick rebuild can reach. That matters because the alternative -- rebuilding five
years of ticks to audit the 1d series -- is several days of API calls, and this
answers a large part of the same question in seconds.

The logic is that Coinbase serves each granularity from the same trades, so a
complete coarse bar must equal the aggregate of the fine bars inside it. Where it
does not, at least one of the two is wrong, with no external reference needed.
That is a weaker claim than a tick rebuild -- it finds disagreement, not which
side is right, and two granularities can share an error and agree -- so a clean
result here is evidence of consistency, not proof of correctness.

Incomplete coarse bars are excluded rather than compared: a day holding 23 of 24
hours legitimately differs from a 1d bar, and reporting that as a mismatch would
bury the real ones. The count of excluded bars is reported, because a series
where most days are incomplete has a different problem worth seeing.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from backtester.core.types import INTERVAL_SECONDS  # noqa: E402

# Prices are compared absolutely; volume relatively. A 0.01 difference in a
# $63,000 BTC print is noise, while 0.01 in a $0.078 DOGE print is not, so the
# price tolerance is scaled by the price itself below.
PRICE_REL_TOL = 1e-9
VOLUME_REL_TOL = 1e-9


def compare(fine: pd.DataFrame, coarse: pd.DataFrame, coarse_seconds: int,
            fine_seconds: int) -> dict:
    """Aggregate `fine` up to `coarse`'s interval and diff the complete bars."""
    expected = coarse_seconds // fine_seconds
    f = fine.assign(b=(fine["timestamp"] // coarse_seconds).astype("int64") * coarse_seconds)
    agg = f.groupby("b").agg(
        open=("open", "first"), high=("high", "max"), low=("low", "min"),
        close=("close", "last"), volume=("volume", "sum"), n=("open", "size"))
    complete = agg[agg["n"] == expected]
    incomplete = len(agg) - len(complete)

    m = coarse.set_index("timestamp").join(complete, rsuffix="_f", how="inner")
    if m.empty:
        return {"compared": 0, "incomplete": incomplete, "fields": {}, "worst": []}

    fields: dict[str, int] = {}
    worst: list[dict] = []
    for field in ("open", "high", "low", "close", "volume"):
        a, b = m[field], m[field + "_f"]
        scale = b.abs().replace(0, 1.0)
        rel = (a - b).abs() / scale
        tol = VOLUME_REL_TOL if field == "volume" else PRICE_REL_TOL
        bad = rel > tol
        fields[field] = int(bad.sum())
        if bad.any():
            k = rel[bad].idxmax()
            worst.append({
                "field": field,
                "when": str(pd.Timestamp(int(k), unit="s", tz="UTC").date()),
                "coarse": float(a.loc[k]),
                "from_fine": float(b.loc[k]),
                "rel": float(rel.loc[k]),
            })
    return {"compared": len(m), "incomplete": incomplete, "fields": fields, "worst": worst}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--assets", default="SOL,BTC,ETH,DOGE,ZEC")
    ap.add_argument("--data-dir", default=str(REPO / "data"))
    ap.add_argument("--report", default=None)
    ap.add_argument(
        "--pairs", default="1h:1d,1m:1h,1m:1d,5m:1h,1m:5m",
        help="fine:coarse interval pairs to check",
    )
    ap.add_argument("--suffix", default="", help="e.g. _last30d for the 1m caches")
    args = ap.parse_args(argv)

    data = Path(args.data_dir)
    lines = [
        "# Candle cross-check — the cache against itself\n\n",
        "Generated by `research/candle_crosscheck.py`. No network: each coarse bar "
        "is compared against the aggregate of the finer bars inside it, over the "
        "**whole history** of each file. Disagreement proves one side is wrong "
        "without saying which; agreement is consistency, not proof.\n",
    ]
    any_bad = False

    for asset in [a.strip().upper() for a in args.assets.split(",") if a.strip()]:
        lines.append(f"\n## {asset}\n\n")
        printed = False
        for pair in args.pairs.split(","):
            fine_i, coarse_i = (p.strip() for p in pair.split(":"))
            fine_p = _resolve(data, asset, fine_i, args.suffix)
            coarse_p = _resolve(data, asset, coarse_i, args.suffix)
            if fine_p is None or coarse_p is None:
                continue
            fine, coarse = pd.read_csv(fine_p), pd.read_csv(coarse_p)
            r = compare(fine, coarse, INTERVAL_SECONDS[coarse_i], INTERVAL_SECONDS[fine_i])
            if not r["compared"]:
                continue
            printed = True
            bad = {k: v for k, v in r["fields"].items() if v}
            if bad:
                any_bad = True
            summary = (", ".join(f"**{v} wrong {k}**" for k, v in bad.items())
                       if bad else "consistent")
            print(f"{asset} {fine_i}->{coarse_i}: {r['compared']} bars, {summary}",
                  file=sys.stderr)
            lines.append(
                f"- `{coarse_p.name}` vs `{fine_p.name}`: {r['compared']} complete "
                f"{coarse_i} bars compared ({r['incomplete']} skipped as incomplete) — "
                f"{summary}\n"
            )
            for w in r["worst"]:
                lines.append(
                    f"    - worst {w['field']}: {w['when']} coarse={w['coarse']:.6f} "
                    f"vs fine={w['from_fine']:.6f} ({w['rel']:.4%})\n"
                )
        if not printed:
            lines.append("- no overlapping interval pairs cached\n")

    if args.report:
        Path(args.report).write_text("".join(lines))
        print(f"\nreport: {args.report}", file=sys.stderr)
    # Non-zero when the cache disagrees with itself, so a wrapper can branch on it.
    return 1 if any_bad else 0


def _resolve(data: Path, asset: str, interval: str, suffix: str) -> Path | None:
    """Cache path for an interval, tolerating the _last30d naming of the 1m files."""
    for candidate in (
        data / f"{asset}_{interval}{suffix}.csv",
        data / f"{asset}_{interval}.csv",
        data / f"{asset}_{interval}_last30d.csv",
    ):
        if candidate.exists():
            return candidate
    return None


if __name__ == "__main__":
    raise SystemExit(main())
